# Generated by Django 3.2.5 on 2021-07-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=100)),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
